version: '3.8'
services:
  db:
    image: mongo
    container_name: db
    restart: always
    environment:
      - MONGO_INITIDB_ROOT_USERNAME=dio
      - MONGO_INITIDB_ROOT_PASSWORD=dio
    ports:
      -"27017:27017"
    volumes:
      - /Users/Gabriel/Desktop/Gits/BootCamp-Claro-DIO/SectionMongoDb/Docker:data/db